### ISSUE TITLE
Track "Principles for Package Repository Security" Current State

### ISSUE THREAD

**Issue by maennchen** [hexpm/hexpm#1290]
OpenSSF [publishes a document called "Principles for Package Repository Security"](https://repos.openssf.org/principles-for-package-repository-security.html) to rate the security of package managers. The list contains a lot of points we should have a look at long-term.

This issue tracks the current state of implementation.

* Security Capabilities of Package Repositories
  * [x] Level 0
  * [ ] Level 1
    * [x] Multi Factor Authentication
    * [ ] Vulnerability Reporting (#957 feature exists; not released on hex.pm)
  * [ ] Level 2
    * [ ] requiring MFA for critical packages
    * [ ] warning users of known security vulnerabilities (#1276)
  * [ ] Level 3
    * [ ] MFA for all maintainers
    * [ ] supporting build provenance for packages
* Authentication
  * [ ] Level 1
    * [x] The package repository requires users to verify their email address.
    * [ ] The package repository documents their account recovery policy.
    * [x] The package repository supports strong multi-factor authentication (MFA) via, at minimum, TOTP.
    * [ ] The package repository notifies maintainers via email for critical account security changes, such as password changes or disabling multi-factor authentication.
    * [ ] The package repository implements account security measures like brute force prevention (even with 2FA attempts)
  * [ ] Level 2
    * [ ] To prevent domain resurrection for account takeover via the recovery process, the package repository detects abandoned email domains.
    * [ ] The package repository supports MFA via phishing-resistant means such as WebAuthn. (#1058)
    * [ ] The package repository requires MFA for packages deemed critical
    * [x] The package repository integrates with public leaked credential databases such as Have I Been Pwned
  * [ ] Level 3
    * [ ] The package repository supports passwordless authentication, such as passkeys. (#1058)
    * [ ] The package repository requires MFA for all maintainers.
    * [ ] The package repository requires phishing-resistant MFA for packages deemed critical
* Authorization
  * [ ] Level 1
    * [x] The package repository allows maintainers to provision API keys scoped to specific packages.
    * [ ] API tokens are prefixed with a package repository-specific identifier. (#1196)
  * [ ] Level 2
    * [ ] The package repository supports role-based access control (RBAC) for maintainers, allowing separate roles for managing users and publishing packages.
  * [ ] Level 3
    * [ ] The package repository provisions short-lived API tokens via an OpenID Connect (OIDC) token exchange (#1193)
    * [ ] The package repository API tokens are integrated into common third-party secret scanning programs. (#1196)
    * [ ] The package repository supports providing [build provenance](https://repos.openssf.org/build-provenance-for-all-package-registries) for packages.
* General Capabilities
  * [ ] Level 1
    * [ ] The package repository has published a vulnerability disclosure policy
    * [ ] The package repository takes steps to prevent typosquatting attacks around package names.
  * [ ] Level 2
    * [ ] The package repository has an unpublish policy to prevent specific versions of a package from being replaced
    * [ ] The package repository allows users to report a package as suspicious or malicious
    * [ ] The package repository takes steps to detect malware
  * [ ] Level 3
    * [ ] Undergo periodic security reviews of package repository infrastructure
    * [ ] The package repository publishes an event transparency log to enable detection of anomalous behaviors
    * [ ] Advisories for malicious packages are published using a standardized machine readable format
* CLI Tooling
  * [x] Level 1
    * [x] The CLI allows installing dependencies that are pinned based on hash, version, etc.
  * [ ] Level 2
    * [ ] The CLI warns of known security vulnerabilities in dependencies when installing packages.  (follow up of #1276)
  * [ ] Level 3
    * [ ] The CLI has functionality to produce SBOMs. (Although here it would make sense that Mix does that and not Hex I think.)
    * [ ] The CLI has functionality to, where possible, automatically remediate known vulnerabilities in dependencies by upgrading them.
    * [ ] The package repository is able to reduce false positives of identified vulnerabilities using static analysis to understand whether a vulnerable code path is actually reachable.

**Comment by maennchen** [comment]
(I might have missed a few boxes to check. I just checked what I was certain would already be done.)

**Comment by ericmj** [comment]
I have marked the following items as done:
* "The package repository supports role-based access control (RBAC) for maintainers, allowing separate roles for managing users and publishing packages."
  * We have a maintainer level and and a full level, the maintainer level can publish packages but cannot manage other owners.
* "The package repository has an unpublish policy to prevent specific versions of a package from being replaced."
  * The policy is to not allow unpublishing.

**Comment by ericmj** [comment]
Thanks for creating this checklist @maennchen, it all looks reasonable and should be something we can work towards.

I have some questions and observations on some of the checklist items.

> The package repository takes steps to detect malware

Can this be expanded upon, what would it look like, do we have examples of other package managers doing this?

> The package repository publishes an event transparency log to enable detection of anomalous behaviors

We have the audit logs today https://hex.pm/packages/ecto/audit-logs. It includes more data on the backend https://hex.pm/packages/ecto/audit-logs than what is currently visible on the website or API so it can be expanded upon. It includes things like the release checksum so you can verify that the release you are downloading is the same as the audit log.

The log is append only but is missing integrity checks in the sense that a malicious actor could modify it and it would be hard to discover. A possible idea to make integrity checks easier would be to build a hash / Merkle tree on top of it and publish it for external verification.

> The CLI has functionality to produce SBOMs. (Although here it would make sense that Mix does that and not Hex I think.)

Is this mix task https://hex.pm/packages/sbom by @voltone enough to satisfy this check? Would we need to integrate it with mix directly or is it fine as a separate package?

> The CLI has functionality to, where possible, automatically remediate known vulnerabilities in dependencies by upgrading them.

What does this mean exactly? We have `mix hex.audit` today and of course `mix deps.update` that will of course automatically update packages when it can. The plan is for `mix hex.audit` to also include reports from https://github.com/hexpm/hexpm/pull/1276. Is that enough?

> The package repository is able to reduce false positives of identified vulnerabilities using static analysis to understand whether a vulnerable code path is actually reachable.

This doesn't really feel in scope for a package manager to me. I think this should be a separate tool that you can integrity in your tool chain. Maybe `mix hex.audit` could use these tools but hard see how that would work before the tools exist.

Do vulnerability reports include things like the exact code location of vulnerabilities so that analysis like this can be done?

**Comment by Ch4s3** [comment]
@maennchen is this list relatively up to date? I'd be happy to pitch in

**Comment by maennchen** [comment]
Yes, this is up to date. For bigger topics we should start with a discussion on how to implement them.

**Comment by Ch4s3** [comment]
@maennchen this ` The package repository supports MFA via phishing-resistant means such as WebAuthn. ` seems relatively self contained. Is there anything non-obvious about it?

**Comment by maennchen** [comment]
@Ch4s3 Yes, 2FA is required for publish via API. Right now this works by sending the OTP code in a HTTP header. So we need to think about a solution for that.

**Comment by ericmj** [comment]
Doing Webauthn in the terminal is not possible so we have to open a browser window. It's also hard (impossible without something like ssh agent?) to cache the auth which means we need to open a browser window for action that requires 2FA today.

This is pretty bad UX imo, so I'm thinking if we can add most of the management tasks to the website such such `mix hex.owner` and add trusted publishing we can minimize the amount of privileged tasks you have to do in the CLI.

If you want to contribute in this area I would suggest adding package ownership management to hex.pm.

**Comment by Ch4s3** [comment]
> If you want to contribute in this area I would suggest adding package ownership management to hex.pm.

@ericmj would this include a flow for inviting people to become users and maintainers on a package?


Also is this issue the place to discuss sub tasks or do you all prefer separate smaller issues?

**Comment by ericmj** [comment]
> would this include a flow for inviting people to become users and maintainers on a package?

 Yes.

> Also is this issue the place to discuss sub tasks or do you all prefer separate smaller issues?

I would suggest creating a new issue, I think this one could get quite long if we discuss individual issues.

**Comment by Ch4s3** [comment]
@ericmj and @maennchen with https://github.com/hexpm/hexpm/issues/1541 closed, what's a good next step to try to tackle here?

**Comment by ericmj** [comment]
Following up on https://github.com/hexpm/hexpm/issues/1327 would be helpful.

I think what's still missing is:
- Email address adding (only the verification email goes to the new address, no security notification to the existing primary)
- Primary email change
- API key creation and revocation

@maennchen Do you agree the above warrants emails? Anything we are missing?

**Comment by maennchen** [comment]
@ericmj That completes the things I had on my list.

**Comment by Ch4s3** [comment]
Ok, I'll take a look at #1327.

**Comment by ericmj** [comment]
@maennchen Is this one done, if not what's left to do?

> Advisories for malicious packages are published using a standardized machine readable format

**Comment by Ch4s3** [comment]
It doesn't look like #1327 is fully done, I don't see api key revoked, email added, or primary email changed notifications.

**Comment by ericmj** [comment]
@Ch4s3 There's still work to be done there so it's up for grabs if you want to work on it 😄

**Comment by Ch4s3** [comment]
on it

**Comment by Ch4s3** [comment]
@maennchen I see you've reopened this, is there a next task that isn't blocked?

**Comment by maennchen** [comment]
What do you mean? There's more still to do than already done.

**Comment by Ch4s3** [comment]
> What do you mean? There's more still to do than already done.

Looking at the check list, I don't have the context to know which things have dependencies on other work or require specific coordination. Like " requiring MFA for critical packages" probably requires deciding on critical packages, but maybe the code can be written first. I'm just not sure.

**Comment by maennchen** [comment]
@Ch4s3 Ah sorry, I misunderstood your question. I thought you’re questioning why the issue was reopened and not if there’s things you can do.

MFA topics I would bench until rebar supports MFA at all.

The next bigger topic is probably Trusted Publishing. I commented with some ideas a while back in #1193.

You could have a look and compare is to current best practices. Especially how we could encode claim requirements into the data model supporting multiple providers. (I would work on the goals / plans first before writing code.)

**Comment by Ch4s3** [comment]
@maennchen is " The package repository supports passwordless authentication, such as passkeys." still open? That old PR has a comment from @ericmj mentioning that there's something on main.

**Comment by maennchen** [comment]
@Ch4s3 Yes, it's still open. But to support it we'll need to implement staged publishing first since we won't be able to do passkeys in a terminal.

I think we should wait with that topic until the current changes are all out and Trusted Publishing is done as well.

If you're looking for a thing to do, we should possibly start looking into SLSA. For that we would need a pure erlang sigstore client library. If you're interested, I'd be happy to give some guidance about where to get started.

**Comment by Ch4s3** [comment]
@maennchen I'd love your input. I'm trying to figure out how to fit this to the new issue template.
