### ISSUE TITLE
Private repositories

### ISSUE THREAD

**Issue by ericmj** [hexpm/hexpm#537]
Overarching issue for tracking progress of private repositories.

### hexpm

  * [x] Add multiple repositories with `Repository` (ffd11d7850b52b243bda660b3c9eb39dd240e277)
  * [x] Permissions through `RepositoryUser` (ffd11d7850b52b243bda660b3c9eb39dd240e277)
  * [x] Authentication on repository CDN tested on Fastly (4cf998d628d9bfb262fdb446a69c4e3b339ed640)
  * [x] Authentication on repository CDN in production (https://github.com/hexpm/hexpm-ops)
  * [x] Display private packages on the  website (#535)
  * [x] Display private packages in the API (#543)
  * [x] Accept published packages for private repos
  * [x] Handle `:repository` in requirements, support depending on packages inside the package repository and "hexpm" (#547)
  * [x] Upload tarball to correct path for private packages, also change `/repo` to plural `/repos` (f7e62110a85c29d5ca6769245abe32faa1ae9112)
  * [x] Build registry for private repositories, make sure to always set `:repository` in registry (cf20f0e31dc02661473c669ccb2b869e9295635b)
  * [x] Managing users and permissions of private repos (#554)
  * [x] Download stats job should register private packages
  * [x] Billing and creation of private repos (#595)
  * [x] New dashboard actions should register in audit log (#595)

### hexdocs

Each repository has its own subdomain, such as myrepo.hexdocs.pm.

  * [ ] Create app for serving private package docs
  * [ ] Set up app on AWS, certificate and, DNS
  * [ ] Authentication against hex.pm

### hex

  * [x] Task for configuring multi repos `mix hex.repo` (hexpm/hex@e01576f28c64af9fae6eb17e2dad30f6efcb303c)
  * [x] Resolve multiple repositories (hexpm/hex@e01576f28c64af9fae6eb17e2dad30f6efcb303c)
  * [x] Setting repo information for package requirements when building package (https://github.com/hexpm/hex/pull/406)
  * [x] Easy setup of private repos from hex.pm through `mix hex.repo` and `mix hex.organization`  (https://github.com/hexpm/hex/pull/407)

**Comment by ericmj** [comment]
Organizations are live. We will track hexdocs tasks separately.
