### ISSUE TITLE
Make audit log public

### ISSUE THREAD

**Issue by ericmj** [hexpm/hexpm#754]
Currently the audit log is only used internally by admins to track past actions. The audit log should be made public for packages to give users insight to the history of the package. For users and organization their private audit logs should be made visible on their respective dashboards.

## TODO

1. [x] Add as paginated new resource to package API endpoint
1. [x] Add as paginated new resource to user API endpoint
1. [x] Add as paginated new resource to organization API endpoint
1. [x] Add to website's package page, it should show the last few actions with a link to a dedicated page of the whole audit log
1. [x] Add to user dashboard, it should the show last few actions with a link to a dedicated page of the whole audit log
1. [x] Add to organization dashboard, it should the show last few actions with a link to a dedicated page of the whole audit log

## Actions belonging to each resource

| action | package | user | organization |
| --- | --- | --- | --- |
| docs.publish | x | x | x |
| docs.revert | x | x | x |
| key.generate | | x | |
| owner.add | x | x | x |
| owner.remove | x | x | x |
| release.publish | x | x | x |
| release.revert | x | x | x |
| release.retire | x | x | x |
| release.unretire | x | x | x |
| email.add | | x | |
| email.primary | | x | |
| email.public | | x | |
| email.gravatar | | x | |
| user.create | | x | |
| user.update | | x | |
| organization.create | | x | x |
| organization.member.add | | x | x |
| organization.member.remove | | x | x |
| organization.member.role | | x | x |
| password.reset.init | | x | |
| password.reset.finish | | x | |
| password.update | | x | |

**Comment by dsdshcym** [comment]
Hi, @ericmj!

Is anyone working on this now? If not, I'd like to take a shot on this one.

**Comment by ericmj** [comment]
No one is working on it afaik, so please go ahead. Thank you!

**Comment by dsdshcym** [comment]
@ericmj cool, thanks!

Here is my plan:

-   Steps
    1.  Query audit logs by user/package/organization (3 PRs)
        1.  Add a module called `Hexpm.Accounts.AuditLogs` as the Context storing AuditLog related functions
        2.  Add a public function `AuditLogs.all_by/1` that can query audit logs for different structs (User/Package/Organization)
            1.  For `User`, query by `belongs_to :user` relationship
            2.  For `Organization`, query by `belongs_to :organization` relationship
            3.  For `Package`, query by `params` which contains the `package_id` (**is it the right way to do it?**)
    2.  Add paginated query results to user/package/organization API responses (3 PRs)
    3.  Add query results to user/package/organization view (3 PRs)
-   Some Questions
    1.  Is `all_by/1` a good function name?
    2.  How do we deal with pagination? My current plan is to add an `all_by/3` function to accept `page, count` and use `Utils.paginate/3`
    3.  How to do visibility control (or authorization)? e.g.
        1.  private audit logs can't be viewed by other users/organizations
        2.  what's the case for private packages?
    4.  Do we need to consider actions? (Or what's the usage of the table "Actions belonging to each resource"?) I have this question because I think we only need to query audit logs by relationships like `user_id`.

**Comment by ericmj** [comment]
> For Package, query by params which contains the package_id (is it the right way to do it?)

Yes. We can move it to a specific field (including a migration that copies the param into the new field), or we can simply add an index to the package_id param for now.

> Is all_by/1 a good function name?

👍 

> How do we deal with pagination?

You can look at how paginate package results in `package.ex`.

> How to do visibility control (or authorization)?

We do this in the controllers. For example https://github.com/hexpm/hexpm/blob/master/lib/hexpm_web/controllers/api/package_controller.ex#L7-L13 for the API and https://github.com/hexpm/hexpm/blob/master/lib/hexpm_web/controllers/package_controller.ex#L57-L60 for the website.

> Do we need to consider actions? 

Querying for id should be enough I think.

**Comment by dsdshcym** [comment]
- [ ] add an index to the package_id params.

I choose to query `params` directly for now in #817. Later, we can migrate to using a separate `package_id` column.

**Comment by dsdshcym** [comment]
Hi, @ericmj!

I'm wondering if we need a separate API endpoint for audit logs. Because adding paginated audit_logs to user/organization/package endpoints feels a bit off to me.

To make audit_logs paginated, my current solution is to add an extra parameter `audit_log_page` to these API endpoints.

I'm proposing adding an `AuditLogsController#index` endpoint which can receive `user_id`/`organization_id`/`package_id`.

**Comment by ericmj** [comment]
Yes, the only way to paginate in a sane way is to have a separate endpoint for audit logs:

* `/api/users/:username/auditlog?page=1`
* `/api/packages/:name/auditlog?page=1`
* `/api/orgs/:name/auditlog?page=1`

**Comment by mischov** [comment]
Sorting of audit logs seems a bit off.

![image](https://user-images.githubusercontent.com/1634632/65443496-da411300-ddf3-11e9-8864-2317d21e7785.png)

Logs from 2019 are descending for the couple shown (there should be more from 2019), but the ones from 2018 are ascending.

**Comment by dsdshcym** [comment]
@mischov The audit logs were not sorted before. 
I opened #858 to sort all audit logs by their `inserted_at` timestamps.

**Comment by dsdshcym** [comment]
Hi @ericmj!

About adding dedicated page to show paginated audit logs for package/user/org, 
since we need to use different authorization logic for package/user/org, 
I think it's better to reuse existing logic (e.g. `OrganizationController.access_organization/4`)

So here is a rough plan for finishing the rest of this feature:
1. Add a `GET /packages/:repository/:name/audit_logs` endpoint, which points to `PackageController.audit_logs/2`.
   This endpoint would render a paginated list similar to https://github.com/hexpm/hexpm/blob/04dc707206b4d8b79e9b6a23f43dc5155c51e6f9/lib/hexpm_web/templates/package/show.html.eex#L162-L171
   And in package show page, there would be a link point to this package audit_logs page
2. Add a `GET /dashboard/audit_logs` endpoint, which points to `Dashboard.AuditLogController.index/2`.
    This endpoint would require login, and shows a paginated list of audit_logs for current user.
    Also, a new item `Recent Activity` would be added to dashboard sidebar.
3. Add a `GET /dashboard/orgs/:dashboard_org/audit_logs` endpoint, which point to `Dashboard.OrganizationController.audit_logs/2`.
    Since there are already too many things under `GET /dashboard/orgs/:dashboard_org` page,
    I'd suggest we create a separate page to show paginated audit_logs.
    In this separate page, there is also a dashboard sidebar, but no highlighted item (so user can click org name to go back.)
    And there is the paginated list to show all audit_logs under panel heading `Recent Activity`.
    Finally, we would show the latest several audit_logs in `GET /dashboard/orgs/:dashboard_org` page, and show a link to the `GET /dashboard/orgs/:dashboard_org/audit_logs` page.
    
I've tried to add a new `GET /audit_logs` and use params like `package_id`, `user_id`, and `org_id` to get audit_logs for different resources.
But I found it difficult to reuse existing authorization logic.

**Comment by ericmj** [comment]
> I've tried to add a new GET /audit_logs and use params like package_id, user_id, and org_id to get audit_logs for different resources.
But I found it difficult to reuse existing authorization logic.

That's understandable, splitting it up on separate endpoints sounds better 👍.

Everything you listed sounds well thought out and looks like a good plan, please go ahead :).

**Comment by ericmj** [comment]
Last piece done in https://github.com/hexpm/hexpm/pull/1245. Thanks everyone!
